AWSTemplateFormatVersion: 2010-09-09
Description: udemy-aws-14days-cfn-template

Resources:
  cfnVPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      Tags:
        - Key: Name
          Value: cfn-udemy-aws-14days-vpc      
